globalConfig:
  author: chenensheng@foresee.com.cn
  open: false
  idType: INPUT
  fileOverride: true
  dateType: ONLY_DATE
dataSourceConfig:
  url: jdbc:mysql://119.29.109.156:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
  driverName: com.mysql.jdbc.Driver
  username: chenes
  password: Ces2311429!
packageConfig:
  parent: com.foresee
  moduleName: ssfm
  entity: model
  service: service
  serviceImpl: service.impl
  mapper: dao
  xml: mapper.xml
  controller: rest.back
  pathInfo:
    entity_path: D:\chenes\project_space\ssfm-mgr\ssfm-mgr-model\src\main\java\com\foresee\ssfm\model
    service_path: D:\chenes\project_space\ssfm-mgr\ssfm-mgr-service\src\main\java\com\foresee\ssfm\service
    service_impl_path: D:\chenes\project_space\ssfm-mgr\ssfm-mgr-service\src\main\java\com\foresee\ssfm\service\impl
    mapper_path: D:\chenes\project_space\ssfm-mgr\ssfm-mgr-model\src\main\java\com\foresee\ssfm\dao
    xml_path: D:\chenes\project_space\ssfm-mgr\ssfm-mgr-model\src\main\resources\com\foresee\ssfm\mapper
    controller_path: D:\chenes\project_space\ssfm-mgr\ssfm-mgr-rest\src\main\java\com\foresee\ssfm\rest\back
strategyConfig:
  naming: underline_to_camel
  columnNaming: underline_to_camel
  entityLombokModel: true
  superMapperClass: com.foresee.icap.framework.data.mybatis.IBaseMapper
  superServiceClass: com.foresee.icap.framework.data.service.IBaseService
  superServiceImplClass: com.foresee.icap.framework.data.service.BaseServiceImpl
  controllerMappingHyphenStyle: true
  restControllerStyle : true
  tablePrefix:
    - t_ssfm_
  include:
    - t_ssfm_pay_detail